set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'tmhedberg/SimpylFold'
Plugin 'vim-scripts/indentpython.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'scrooloose/syntastic'
Plugin 'nvie/vim-flake8'
Plugin 'jnurmine/Zenburn'
Plugin 'altercation/vim-colors-solarized'
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'tpope/vim-fugitive'
Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}

"Put all plugins before this line
call vundle#end()
filetype plugin indent on
py << EOF
import os
import sys
if 'VIRTUAL_ENV' in os.environ:
  project_base_dir = os.environ['VIRTUAL_ENV']
  activate_this = os.path.join(project_base_dir, 'bin/activate_this.py')
  execfile(activate_this, dict(__file__=activate_this))
EOF
let python_highlight_all=1
syntax enable
set encoding=utf-8
set number
set numberwidth=5
set tabstop=4
set autoindent
set expandtab
set shiftwidth=4
set cursorline
set showmatch
set showcmd
set ruler
set laststatus=2
set autoread
set autowrite
set ignorecase
set smartcase
set hlsearch
nnoremap <silent> <leader>, :noh<cr> " Stop highlight after searching
nnoremap j gj
nnoremap k gk
nnoremap <tab> %
vnoremap <tab> %
set incsearch
set showmatch
set list listchars=tab:»·,trail:.,nbsp:.
set diffopt+=vertical
" relative numbering
set rnu
function! ToggleNumbersOn()
    set nu!
    set rnu
endfunction
function! ToggleRelativeOn()
    set rnu!
    set nu
endfunction
autocmd FocusLost * call ToggleRelativeOn()
autocmd FocusGained * call ToggleRelativeOn()
autocmd InsertEnter * call ToggleRelativeOn()
autocmd InsertLeave * call ToggleRelativeOn()



"set background=dark
colorscheme zenburn
call togglebg#map("<F5>")
set foldmethod=indent
set foldlevel=99
highlight BadWhitespace ctermbg=red guibg=red
noremap <space> za
map <C-F> :NERDTreeToggle<CR>
let g:SimpylFold_docstring_preview=1
let NERDTreeIgnore=['\.pyc$', '\~$']
au BufNewFile,BufRead *.py 
    \ setlocal tabstop=4 softtabstop=4 shiftwidth=4 textwidth=79
    \ formatoptions=qnr1 wrapmargin=0 colorcolumn=+1
    \ expandtab autoindent fileformat=unix
au BufNewFile,BufRead *.py,*.pyw,*.c.*.h match BadWhitespace /\s\+$/
au BufNewFile,BufRead *.js,*.html,*.css
    \ set tabstop=2 softtabstop=2 shiftwidth=2
au BufNewFile,BufRead *.sh,*.bash,*.ksh
    \ set tabstop=4 softtabstop=4 shiftwidth=4
    
au vimenter * NERDTree
au bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
